#!/bin/bash
#
source "/gale/netapp/home/seq/bin/demux/demux-constants"

#RSYNCED="/gale/netapp/seq2/illumina_runs/.status/rsynced"
#UPLOADED="/gale/netapp/seq2/illumina_runs/.status/uploaded"
#ARCHIVED="/gale/netapp/seq2/illumina_runs/.status/archived"

#ARCHIVED_D4="/gale/oberon/data4/.archived"

#RSYNCED_R2="/gale/raidix/rdx-2/illumina_runs/.status/rsynced"
#UPLOADED_R2="/gale/raidix/rdx-2/illumina_runs/.status/uploaded"
#ARCHIVED_R2="/gale/raidix/rdx-2/illumina_runs/.status/archived"

#RSYNCED_HOME="/gale/netapp/home/seq/.status/rsynced"
#UPLOADED_HOME="/gale/netapp/home/seq/.status/uploaded"
#ARCHIVED_HOME="/gale/netapp/home/seq/.status/archived"

timestamp="$(date "+%y%m%d%H%M%S")"
TS=$timestamp

echo "Backing up rsynced log to $RSYNCED_R2"-"$TS"
cp $RSYNCED $RSYNCED_R2"-"$TS

echo "Backing up rsynced log to $RSYNCED_HOME"-"$TS"
cp $RSYNCED $RSYNCED_HOME"-"$TS

echo "Backing up uploaded log to $UPLOADED_R2"-"$TS"
cp $UPLOADED $UPLOADED_R2"-"$TS

echo "Backing up uploaded log to $UPLOADED_HOME"-"$TS"
cp $UPLOADED $UPLOADED_HOME"-"$TS

echo "Backing up archived log to $ARCHIVED_R2"-"$TS"
cp $ARCHIVED $ARCHIVED_R2"-"$TS

echo "Backing up archived log to $ARCHIVED_HOME"-"$TS"
cp $ARCHIVED $ARCHIVED_HOME"-"$TS

echo "Updating archived log with archived log from sculpin"
cp $ARCHIVED_D4 $ARCHIVED
