#!/bin/bash
#
source "/gale/netapp/home/seq/bin/demux/demux-constants"

timestamp="$(date "+%y%m%d%H%M%S")"
TS=$timestamp

echo "Backing up rsynced log to $RSYNCED_R2"-"$TS"
cp $RSYNCED $RSYNCED_R2"-"$TS

echo "Backing up rsynced log to $RSYNCED_S2"-"$TS"
cp $RSYNCED $RSYNCED_S2"-"$TS

echo "Backing up uploaded log to $UPLOADED_R2"-"$TS"
cp $UPLOADED $UPLOADED_R2"-"$TS

echo "Backing up uploaded log to $UPLOADED_S2"-"$TS"
cp $UPLOADED $UPLOADED_S2"-"$TS

echo "Backing up archived log to $ARCHIVED_R2"-"$TS"
cp $ARCHIVED $ARCHIVED_R2"-"$TS

echo "Backing up archived log to $ARCHIVED_S2"-"$TS"
cp $ARCHIVED $ARCHIVED_S2"-"$TS

echo "Backing up deeparchived log to $DEEPARCHIVED_R2"-"$TS"
cp $DEEPARCHIVED $DEEPARCHIVED_R2"-"$TS

echo "Backing up deeparchived log to $DEEPARCHIVED_S2"-"$TS"
cp $DEEPARCHIVED $DEEPARCHIVED_S2"-"$TS

#echo "Updating archived log with archived log from sculpin"
#sync-archived-log
#cp $ARCHIVED_D4 $ARCHIVED
