#!/bin/bash
#input: bcl2fastq_command line string
#output: bcl2fastq-config file containing variables for the run

#dependencies
source  ~/bin/demux/var2file
source ~/bin/demux/demux-constants

#parameter passed to script
bcl2fastq_commandline=$1

if ! echo $bcl2fastq_commandline | grep -q bcl2fastq ; then
  echo "Argument provided does not appear to be a bcl2fastq commandline!"
  exit 1
fi

bcl_path="$(echo $bcl2fastq_commandline \
  | awk '{print $4}')"

run_dir="$(echo $bcl_path | awk -F/ '{print $NF}')"

demux_config_dir="$DEMUX_CONFIG_PARENT/$run_dir"

config_path="$demux_config_dir/$CONFIG"

mkdir -p $demux_config_dir

echo "#!/bin/bash" > "$(echo $config_path)"

var2file "bcl2fastq_commandline" "$(echo $config_path)"

var2file "bcl_path" $(echo $config_path)

var2file "run_dir" $(echo $config_path)

var2file "demux_config_dir" $(echo $config_path)

samplesheet_path="$(echo $bcl2fastq_commandline \
  | awk '{print $6}')"
var2file "samplesheet_path" $(echo $config_path)

fastq_path="$(echo $bcl2fastq_commandline \
  | awk '{print $8}')"
var2file "fastq_path" $(echo $config_path)

fastq_dir="$(echo $fastq_path | awk -F/ '{print $NF}')"
var2file "fastq_dir" $(echo $config_path)

log_path="$(echo $bcl2fastq_commandline \
  | awk 'END{print $NF}')"
var2file "log_path" $(echo $config_path)

instrument="$(echo $bcl2fastq_commandline \
  | awk -F"/" '{print $NF}' \
  | awk -F"_" '{print $2}')"
var2file "instrument" $(echo $config_path)

#samplesheet_columns="$(tail -n 1 "$samplesheet_path" | awk -F, '{print NF}')"

demux_log_file="$(echo $bcl2fastq_commandline | awk -F"/" '{print $NF}')"
var2file "demux_log_file" $(echo $config_path)

#instrument specific variables
if [ $instrument == "M00412" ]; then
  flowcell="$(echo ${demux_log_file: -22:5})"  
  qsub_dir="$(echo ${demux_log_file: -22:18})"
  run_year="$(echo ${demux_log_file: -51:2})"
  pause_demux_comp_check=60
else
  flowcell="$(echo ${demux_log_file: -26:9})"
  qsub_dir="$(echo ${demux_log_file: -26:22})"
  run_year="$(echo ${demux_log_file: -46:2})"
  pause_demux_comp_check=900
fi

var2file "flowcell" $(echo $config_path)

var2file "qsub_dir" $(echo $config_path)

run_year="20"$run_year
var2file "run_year" $(echo $config_path)

var2file "pause_demux_comp_check" $(echo $config_path)

versity_year_path="$VERSITY/$run_year"
var2file "versity_year_path" $(echo $config_path)

qsub_path="$QSUB/$qsub_dir"
var2file "qsub_path" $(echo $config_path)

suffix="_versity_fastq"

qsub_versity_fastq_dir="$qsub_dir$suffix"
var2file "qsub_versity_fastq_dir" $(echo $config_path)

qsub_versity_fastq_path="$QSUB_V/$qsub_versity_fastq_dir"
var2file "qsub_versity_fastq_path" $(echo $config_path)

suffix="_versity_bcl"

qsub_versity_bcl_dir="$flowcell$suffix"
var2file "qsub_versity_bcl_dir" $(echo $config_path)

qsub_versity_bcl_path="$QSUB_V/$qsub_versity_bcl_dir"
var2file "qsub_versity_bcl_path" $(echo $config_path)

rsync_fastq_commandline="rsync -avsz $fastq_path $versity_year_path"
var2file "rsync_fastq_commandline" $(echo $config_path)

versity_fastq_path="$versity_year_path/$fastq_dir"
var2file "versity_fastq_path" $(echo $config_path)

rsync_bcl_commandline="rsync -avsz $bcl_path $versity_year_path"
var2file "rsync_bcl_commandline" $(echo $config_path)

versity_bcl_path="$versity_year_path/$run_dir"
var2file "versity_bcl_path" $(echo $config_path)

suffix="_upload_fastq"

qsub_upload_fastq_dir="$qsub_dir$suffix"
var2file "qsub_upload_fastq_dir" $(echo $config_path)

qsub_upload_fastq_path="$QSUB_U/$qsub_upload_fastq_dir"
var2file "qsub_upload_fastq_path" $(echo $config_path)

fastq_tar_path="$TAR_PARENT/$fastq_dir.$EXT"
var2file "fastq_tar_path" $(echo $config_path)

upload_fastq_commandline="$TAR_COMMAND $fastq_tar_path $fastq_path && $CLOUD_COMMAND $fastq_tar_path && rm -v $fastq_tar_path"
var2file "upload_fastq_commandline" $(echo $config_path)

suffix="_upload_bcl"

qsub_upload_bcl_dir="$flowcell$suffix"
var2file "qsub_upload_bcl_dir" $(echo $config_path)

qsub_upload_bcl_path="$QSUB_U/$qsub_upload_bcl_dir"
var2file "qsub_upload_bcl_path" $(echo $config_path)

bcl_tar_path="$TAR_PARENT/$run_dir.$EXT"
var2file "bcl_tar_path" $(echo $config_path)

upload_bcl_commandline="$TAR_COMMAND $bcl_tar_path $bcl_path && $CLOUD_COMMAND $bcl_tar_path && rm -v $bcl_tar_path"
var2file "upload_bcl_commandline" $(echo $config_path)

thumbnail_path="$bcl_path/Thumbnail_Images"
var2file "thumbnail_path" $(echo $config_path)

echo $config_path
