#!/bin/bash
#

#source ~/bin/demux/configure-bcl2fastq
source "/gale/netapp/home/seq/bin/demux/demux-constants"
source "/gale/netapp/home/seq/bin/demux/date-time"
source "/gale/netapp/home/seq/bin/demux/submit2q"
source "/gale/netapp/home/seq/bin/demux/var2file"

#i5 index should be treated as a read and not an index so use Y instead of I
#for atacseq
#mkfastqopts="--qc --use-bases-mask Y*,I8N*,Y*,Y*" #--ignore-dual-index --use-bases-mask Y*,I8N*,N*,Y*"
#for dna/rna
#mkfastqopts="--qc --ignore-dual-index --use-bases-mask Y*,I8N*,N*,Y*"
#8 bases sequenced for I7
#mkfastqopts="--barcode-mismatches 0 --qc --ignore-dual-index " # --use-bases-mask Y26N*,I*,N*,Y*"
#for dna or rna with longer than 28 base read 1 and an index read 2, use cellranger-dna
mkfastqopts="--qc --ignore-dual-index --use-bases-mask Y28N*,I8N*,N*,Y*"

#--use-bases-mask=Y26,I8,Y151

proc_threads="16"
read_threads="4"
write_threads="4"
VMEM="6G"

usage() {
echo "Usage: demux-run -s /gale/netapp/seq2/illumina_runs/.samplesheets/180709_K00161_0224_AHVMNJBBXX/SampleSheet_180709_K00161_0224.csv -O \"-p 16\""
echo "-s        path to samplesheet file"
echo "-p        number of processing threads. Default: 16"
echo "-r        number of reading threads. Default: 4"
echo "-w        number of writing threads. Default: 4"
echo "-v        h_vmem to use per proc. Default: 6G"
echo "-O        additional bcl2fastq options"
echo "-m        select cellranger mkfastq script. options:"
echo "            a: cellranger-atac"
echo "            c: cellranger"
echo "            d: cellranger-dna"
echo "-M        email notice recipients, comma separated list, enclosed in quotes"
echo "-n        do not backup files"
echo "-h        display this help message"
}

while getopts ":s:p:r:w:v:O:m:M:nh" opt; do
  case $opt in
    s) 
      SAMPLESHEET_PATH=$OPTARG
      ;;
    p)
      proc_threads=$OPTARG
      ;;
    r)
      read_threads=$OPTARG
      ;;
    w)
      write_threads=$OPTARG
      ;;
    v) 
      VMEM=$OPTARG
      ;;
    O)
      bclopts=$OPTARG
      ;;
    m)
      mkfastq_vers=$OPTARG
      ;;
    M)
      mail_to=$OPTARG
      ;;
    n)
      backup="no"
      ;;
    h) 
      usage
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      usage
      exit 1
      ;;
  esac
done

echo "$(date_time) INFO: bclopts: $bclopts"
echo "$(date_time) INFO: mkfastqopts: $mkfastqopts"

threads="$(($proc_threads + $read_threads + $write_threads))"

#generate bcl2fastq command line
if [ ! -z ${mkfastq_vers+x} ] ; then
  bcl2fastq_commandline=$(demux-commandline -s "$SAMPLESHEET_PATH" -t "$proc_threads" -r "$read_threads" -w "$write_threads" -O "$mkfastqopts" -m "$mkfastq_vers")
else
  bcl2fastq_commandline=$(demux-commandline -s "$SAMPLESHEET_PATH" -t "$proc_threads" -r "$read_threads" -w "$write_threads" -O "$bclopts")
fi

#check demux-commandline script exit status
if [ $(echo $?) -eq 1 ] ; then
  echo "$bcl2fastq_commandline"
  exit 1
fi

echo "$(date_time) INFO: Command-line invocation: $bcl2fastq_commandline"

#parse variables from bcl2fastq command line,
#write them to config file,
#and source the file for use below

source $(configure-bcl2fastq "$bcl2fastq_commandline") || exit 1

#[ -z $cc ] && cc="$mail_to" || cc=$(echo "$cc,$mail_recipients")
if [ ! -z "$mail_to" ] && [ -z "$cc" ]; then cc="$mail_to"; elif [ ! -z "$mail_to" ] && [ ! -z "$cc" ]; then cc="$(echo "$cc,$mail_to")";fi
var2file "cc" $(echo $config_path)

echo "$(date_time) INFO: Making qsub directory: $qsub_path"

mkdir $qsub_path

cd $qsub_path

echo "$(date_time) INFO: Creating wrapper script $qsub_path/$QSUB_COMMANDS_SCRIPT"

#write bcl2fastq_commandline to commands script
echo "$bcl2fastq_commandline" >> $qsub_path/$QSUB_COMMANDS_SCRIPT

echo "$(date_time) INFO: Submitting job to queue"

echo "$(date_time) INFO: Queue config file $QUEUECONFIG"

if [ "$mkfastq" = true  ] || [ "$mkfastq_dna" = true  ] ; then
  2q -p "demux" -c $QUEUECONFIG -t "16" -v "8G" #-M "$cc"
  echo "$(date_time) INFO: 2q -p "demux" -c $QUEUECONFIG -t "16" -v "8G"" # -M "$cc""
else
  2q -p "demux" -c $QUEUECONFIG -t "$threads" -v "$VMEM" # -M "$cc"
  echo "$(date_time) INFO: 2q -p "demux" -c $QUEUECONFIG -t "$threads" -v "$VMEM"" # -M "$cc""
fi

node=$(qstatx | grep "$qsub_dir")

echo $node

jobid="$(echo $node | awk '{print $1}')"
var2file "jobid" $(echo $config_path)

source $config_path

submission_file="$qsub_path/$COMMANDS2SUBMIT"

echo "$(date_time) INFO: $submission_file"

qsub_command=$(cat $submission_file)

echo "$(date_time) INFO: $qsub_command"

#wait for the fastq directory to be created
until [ -d $fastq_path ]; do 
  echo "$(date_time) *********** DO NOT PRESS CTRL-C! **************"
  echo "$(date_time) Waiting 60 seconds for creation of $fastq_path."
  sleep 60 ; 
done ; 

echo "$(date_time) INFO: Writing config files"

#write a file containing bcl_path to the fastq directory
echo $bcl_path >> $fastq_path/$BCL_PATH_FILE

#copy samplesheet to fastq directory
cp $samplesheet_path $fastq_path/$SAMPLESHEET_NAME

#write bcl2fastq_commandline to BCL and Unaligned directory
echo "$bcl2fastq_commandline" >> $fastq_path/$qsub_dir-$FASTQ_COMMAND_FILE
echo "$bcl2fastq_commandline" >> $bcl_path/$qsub_dir-$FASTQ_COMMAND_FILE

#copy xml files to fastq directory
[ -f $bcl_path/RunInfo.xml ] && cp $bcl_path/RunInfo.xml $fastq_path/RunInfo.xml
[ -f $bcl_path/RunParameters.xml ] && cp $bcl_path/RunParameters.xml $fastq_path/RunParameters.xml
[ -f $bcl_path/runParameters.xml ] && cp $bcl_path/runParameters.xml $fastq_path/runParameters.xml 

#node=$(qstatx | grep "${qsub_dir:0:10}")
#node=$(qstatx | grep "$qsub_dir")

#write a file containing the qsub node to the fastq dir
echo "$node" > $fastq_path/"$qsub_dir"-qstat.txt
echo "$node" > $bcl_path/"$qsub_dir"-qstat.txt

#write file containing qsub script to fastq dir
echo "$qsub_command" >$fastq_path/"$qsub_dir"-qsub.txt
echo "$qsub_command" >$bcl_path/"$qsub_dir"-qsub.txt

echo "$(date_time) INFO: Demux Started. Sending notification"

{
  echo -e "Demux Started.\n" 
  echo -e "Command-line invocation:" ; \
  echo -e "$bcl2fastq_commandline\n" ; \
  echo -e "SGE invocation:" ; \
  echo -e "$qsub_command\n" ; \
  echo -e "jobnumber:" ; \
  echo -e "$node\n"
  echo -e "bcl2fastq configuration:" ; \
  echo -e "$configuration"
} | mailx -s "$bcl_path" "$RECIPIENT" # -c "$cc"

#
# loop until demux completes by
# checking log for success

until grep -Eq "$STOPSTR10X|$STOPSTR" $log_path
do
    sleep $pause_demux_comp_check
done

log_message=$(grep -E "$STOPSTR10X|$STOPSTR" $log_path)

if echo $log_message | grep -q $COMPLETESTR ; then

  echo "$log_message"
  
  echo "$(date_time) INFO: Sending demux completion notification."

  sleep 30

  demux-completion-notification -c $config_path

  #remove thumbnail images prior to backing up
  echo "$(date_time) INFO: Removing Thumbnail_Images directory if present."
  #[[ -d $thumbnail_path/L001 || -d $thumbnail_path/L002 || \
  #   -d $thumbnail_path/L003 || -d $thumbnail_path/L004 || \
  #   -d $thumbnail_path/L005 || -d $thumbnail_path/L006 || \
  #   -d $thumbnail_path/L007 || -d $thumbnail_path/L008 ]] && \
     rm -rfv $thumbnail_path

  sleep 60

  [ "$backup" = "no" ] && exit 0

  #rsync bcl to versity
  echo
  echo "$(date_time) INFO: Backing up bcl to versity:"
  echo $rsync_bcl_commandline
  echo
  submit2q "$rsync_bcl_commandline" "$qsub_versity_bcl_path" "$qsub_versity_bcl_dir" "$versity_bcl_path" "$bcl_dir" "$config_path"
  
  #rsync fastq to versity
  echo
  echo "$(date_time) INFO: Backing up fastq to versity:"
  echo $rsync_fastq_commandline
  echo
  submit2q "$rsync_fastq_commandline" "$qsub_versity_fastq_path" "$qsub_versity_fastq_dir" "$versity_fastq_path" "$fastq_dir" "$config_path"
  
  #tar and upload bcl
  echo
  echo "$(date_time) INFO: Tarring and uploading bcl to cloud:"
  echo $upload_bcl_commandline
  echo
  submit2q "$upload_bcl_commandline" "$qsub_upload_bcl_path" "$qsub_upload_bcl_dir" "$bcl_tar_path" "$bcl_dir" "$config_path"
  
  #tar and upload fastq
  echo
  echo "$(date_time) INFO: Tarring and uploading bcl to cloud:"
  echo $upload_fastq_commandline
  echo
  submit2q  "$upload_fastq_commandline" "$qsub_upload_fastq_path" "$qsub_upload_fastq_dir" "$fastq_tar_path" "$fastq_dir" "$config_path"
 
fi

echo "$(date_time) INFO: Demux complete."

exit 0

