#!/bin/bash
#

QSUB_PARENT="/gale/netapp/seq2/illumina_runs/.qsub"
BCL_PATH_FILE="bcl_path.txt"

usage() {
echo "Usage: demux-run -s /gale/netapp/seq2/illumina_runs/.samplesheets/180709_K00161_0224_AHVMNJBBXX/SampleSheet_180709_K00161_0224.csv"
echo "-s	path to samplesheet file"
echo "-O	additional bcl2fastq options"
echo "-h	display this help message"
}

while getopts ":s:O:h" opt; do
  case $opt in
    s) 
      SAMPLESHEET_PATH=$OPTARG
      ;;
    O)
      bclopts=$OPTARG
      ;;
    h) 
      usage
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      usage
      exit 1
      ;;
  esac
done

echo "bclopts: $bclopts"

#generate bcl2fastq command line
bcl2fastq_command_line=$(demux-commandline -s "$SAMPLESHEET_PATH" -O "$bclopts")

#check demux-commandline script exit status
if [ $(echo $?) -eq 1 ] ; then
  echo "$bcl2fastq_command_line"
  exit 1
fi

#parse command line
bcl_path=$(echo $bcl2fastq_command_line \
  | awk '{print $4}')

samplesheet_path=$(echo $bcl2fastq_command_line \
  | awk '{print $6}')

fastq_path=$(echo $bcl2fastq_command_line \
  | awk '{print $8}')

log_path=$(echo $bcl2fastq_command_line \
  | awk 'END{print $NF}')

instrument=$(echo $bcl2fastq_command_line \
  | awk -F"/" '{print $NF}' \
  | awk -F"_" '{print $2}')

if [ $instrument == "M00412" ]; then
  qsub_dir=$(echo $bcl2fastq_command_line \
    | awk -F"/" '{print $NF}' \
    | awk -F"_" '{print $4}' \
    | awk -F"-" '{print $NF}')
else
  qsub_dir=$(echo $bcl2fastq_command_line \
    | awk -F"/" '{print $NF}' \
    | awk -F"_" '{print $4}' \
    | awk '{print substr($NF,2,9)}')
fi

qsub_dir+=$(echo $bcl2fastq_command_line \
  | awk -F"/" '{print $NF}' \
  | awk -F"_" '{print substr($NF,3,8)}')

qsub_path="$QSUB_PARENT/$qsub_dir"

mkdir $qsub_path

cd $qsub_path

#source ~/.bash_profile in wrapper script
echo "source /gale/netapp/home/seq/.bash_profile" > $qsub_path/pipeline

#write bcl2fastq_command_line to pipeline wrapper script
echo "$bcl2fastq_command_line" >> $qsub_path/pipeline

#write demux-completion-notification to wrapper script
#demux-completion-notification -f /gale/netapp/seq2/illumina_runs/180727_K00161_0227_BHW2MVBBXX_180730171425 -b /gale/netapp/seq2/illumina_runs/180727_K00161_0227_BHW2MVBBXX
#echo "bash /gale/netapp/home/seq/bin/demux/demux-completion-notification -f $fastq_path -b $bcl_path" >> $qsub_path/pipeline
echo "demux-completion-notification -f $fastq_path -b $bcl_path" >> $qsub_path/pipeline

#write qsub commands script that calls pipeline
echo "bash $qsub_path/pipeline" > $qsub_path/commands

echo "Submitting job to queue"
2q

#wait for the fastq directory to be created
until [ -d $fastq_path ]; do 
  echo "Waiting 60 seconds for creation of $fastq_path."
  sleep 60 ; 
done ; 

echo "Writing config files"

#write a file containing bcl_path to the fastq directory
echo $bcl_path >> $fastq_path/$BCL_PATH_FILE

#copy samplesheet to fastq directory
cp $samplesheet_path $fastq_path

node=$(qstat | grep "${qsub_dir:0:10}")
#write a file containing the qsub node to the fastq dir
echo "$node" > $fastq_path/node.txt
echo $bcl2fastq_command_line
echo "$qsub_path"
exit 0
