#!/bin/bash

run_path="$(pwd)"
run_name="$(basename $run_path)"
RUNFOLDER="$run_name"
UNALIGNED="$run_path"
INSTRUMENT=$(echo $run_name | awk -F"_" '{print $2}')
FLOWCELL=$(echo $UNALIGNED | awk -F"_" '{print $5}')
if [ ! $INSTRUMENT == "M00412" ]; then
  FLOWCELL=${FLOWCELL:1}
fi
LANEBARCODE="$UNALIGNED/Reports/html/$FLOWCELL/all/all/all/laneBarcode.html"
RECIPIENT="jnery@salk.edu"

projects="$(lanebarcode-projects -l $LANEBARCODE)"
samples="$(lanebarcode-samples -l $LANEBARCODE)"

(echo -e "Demux complete. Path to fastq:" ; \
  echo -e "$UNALIGNED\n" ; \
  echo -e "Samples:" ; \
  echo -e "$samples\n" ; \
  echo -e "Projects:" ; \
  echo -e "$projects\n") \
| mailx -s "$RUNFOLDER" -a "$LANEBARCODE" -c "$CC" "$RECIPIENT"
