#!/bin/bash

#CC="cluo@salk.edu,castanon@salk.edu"
CC=""
RUNFOLDER="180709_K00161_0224_AHVMNJBBXX"
UNALIGNED="/gale/netapp/seq2/illumina_runs/180709_K00161_0224_AHVMNJBBXX_180718131851"
FLOWCELL=$(echo $UNALIGNED | awk -F "_" '{print $5}')
FLOWCELL=${FLOWCELL:1}
LANEBARCODE="$UNALIGNED/Reports/html/$FLOWCELL/all/all/all/laneBarcode.html"
RECIPIENT="jnery@salk.edu"

echo "$UNALIGNED" | mailx -s "$RUNFOLDER" -a "$LANEBARCODE" -c "$CC" "$RECIPIENT"
#echo "$UNALIGNED" | mailx -s "$RUNFOLDER" -a "$LANEBARCODE" "$RECIPIENT"

#echo "/gale/netapp/seq3/illumina_runs/fastqs/180608_K00161_0221_BHVCYYBBXX/" | mailx -s "180608_K00161_0221_BHVCYYBBXX" -a "/gale/netapp/seq3/illumina_runs/fastqs/180608_K00161_0221_BHVCYYBBXX/Reports/html/HVCYYBBXX/all/all/all/laneBarcode.html" -c "bawang@salk.edu,castanon@salk.edu" jnery@salk.edu
