#!/bin/bash
#
#Generates the command line for Demultiplexing a run 
#using the given SampleSheet.csv
#
#It must be invoked in the run folder
#
#The fastqs will be written to a directory in the 
#OUTPUT_PARENT directory, which is defined below. 
#It is assigned the directory name of the run folder 
#with a timestamp suffix.
#
#The nohup is redirected to a log file in the LOG_PARENT
#directory defined below and assigned a filename as 
#described previously.
#

#Constants
OUTPUT_PARENT="/gale/oberon/data11"
SAMPLESHEET_PARENT="/gale/netapp/seq2/illumina_runs/.samplesheets"
LOG_PARENT="/gale/netapp/seq2/illumina_runs/.demux_logs"
QSUB_PARENT="/gale/netapp/seq2/illumina_runs/.qsub"
RTA_COMPLETE="RTAComplete.txt"

timestamp="$(date "+%y%m%d%H%M%S")"
run_path="$(pwd)"
run_name="$(basename $run_path)"
run_name_ts="${run_name}_$timestamp"
output_path="$OUTPUT_PARENT/$run_name_ts"
log_name="$run_name_ts.txt"
log_path="$LOG_PARENT/$log_name"
flowcell="$(echo $run_name | awk -F_ '{print $NF}')"
flowcell_ts="${flowcell}_$timestamp"

usage() {
echo "eg, demux-commandline -s SampleSheet.csv"
echo "-s, path to tiny-bcl samplesheet in .samplesheets directory: /gale/netapp/seq2/illumina_runs/.samplesheets"
echo "-O, additional options enclosed in quotes"
echo "-h, this help message"
}

while getopts ":s:O:h" opt; do
  case $opt in
    s) 
      SAMPLESHEET_PATH=$OPTARG
      ;;
    O)
      bclopts=$OPTARG
      ;;
    h) 
      usage
      exit
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      usage
      exit
      ;;
  esac
done

if [ ! -f "$run_path/$RTA_COMPLETE" ] ; then
  echo "This does not appear to be a valid run directory!"
  exit 1
fi

samplesheet="$SAMPLESHEET_PATH"

if [ ! -f $samplesheet ]; then
  echo "Error! $samplesheet not found!"
  exit 1
fi



bcl2fastq_command_line="cellranger mkfastq \
  --ignore-dual-index \
  --run $run_path \
  --id $flowcell_ts \
  --csv $samplesheet \
  --output-dir $output_path \
  &> $log_path"

echo $bcl2fastq_command_line
exit 0
