#!/bin/bash

source "/gale/netapp/home/seq/bin/demux/demux-constants"
source "/gale/netapp/home/seq/bin/demux/date-time"

COMMAND_LINE_FILE="*command_line.txt"
QSTAT_FILE="*qstat.txt"
QSUB_FILE="*qsub.txt"

usage() {
echo "Usage: demux-notify -c /gale/netapp/seq2/illumina_runs/.config/180709_K00161_0224_AHVMNJBBXX"
echo "-c	path to bcl2fastq config file."
echo "-h	this help message"
}

while getopts ":f:c:h" opt; do
  case $opt in
    c)config_path=$OPTARG
      ;;
    h)
      usage
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      usage
      exit 1
      ;;
  esac
done

source "$config_path"

stats="$bcl_path/Stats/Stats.json"

#cat Stats.json | jq '.ReadInfosForLanes[0].ReadInfos[0].NumCycles'

[ -f $runparameters ] || runparameters="$bcl_path/RunParameters.xml"

projects="$(lanebarcode-projects -l $lanebarcode)"

samples="$(lanebarcode-samples -l $lanebarcode)"

qsub_command="$(cat $fastq_path/$QSUB_FILE)"

node="$(cat $fastq_path/$QSTAT_FILE)"

jobid="$(awk '{print $1}' $fastq_path/$QSTAT_FILE)"

jobmetrics="$qsub_path/job_metrics.txt"

qacct -d 2 -o seq -j | grep -A 34 $jobid | grep -E "jobnumber|_time|slots|^mem|maxvmem" > $jobmetrics

jobnumber=$(grep "jobnumber" $jobmetrics)
start_time=$(grep "start_time" $jobmetrics)
end_time=$(grep "end_time" $jobmetrics)
slots=$(grep "slots" $jobmetrics)
mem=$(grep "^mem" $jobmetrics)
maxvmem=$(grep "maxvmem" $jobmetrics)

echo $bcl2fastq_commandline

{ 
  echo -e " Path to fastq:" ; \
  echo -e "$fastq_path\n" 
} | mailx -s "$mentions" -a "$lanebarcode" -r "$RECIPIENT" "$trello" 
