#!/bin/bash

RUNFOLDER="180621_K00161_0223_AHVL2HBBXX"
UNALIGNED="/gale/netapp/seq2/illumina_runs/180621_K00161_0223_AHVL2HBBXX_180702183037"
FLOWCELL=$(echo $UNALIGNED | awk -F "_" '{print $5}')
FLOWCELL=${FLOWCELL:1}
LANEBARCODE="$UNALIGNED/Reports/html/$FLOWCELL/all/all/all/laneBarcode.html"
CC="mzander@salk.edu,castanon@salk.edu,hsong@salk.edu,mhariharan@salk.edu,barragan@salk.edu"
#CC=""
RECIPIENT="jnery@salk.edu"

echo "$UNALIGNED" | mailx -s "$RUNFOLDER" -a "$LANEBARCODE" -c "$CC" "$RECIPIENT"
#echo "$UNALIGNED" | mailx -s "$RUNFOLDER" -a "$LANEBARCODE" "$RECIPIENT"

#echo "/gale/netapp/seq3/illumina_runs/fastqs/180608_K00161_0221_BHVCYYBBXX/" | mailx -s "180608_K00161_0221_BHVCYYBBXX" -a "/gale/netapp/seq3/illumina_runs/fastqs/180608_K00161_0221_BHVCYYBBXX/Reports/html/HVCYYBBXX/all/all/all/laneBarcode.html" -c "bawang@salk.edu,castanon@salk.edu" jnery@salk.edu
