#!/bin/bash

source "/gale/netapp/home/seq/bin/demux/demux-constants"
source "/gale/netapp/home/seq/bin/demux/date-time"

COMMAND_LINE_FILE="*command_line.txt"
QSTAT_FILE="*qstat.txt"
QSUB_FILE="*qsub.txt"

usage() {
echo "Usage: demux-notify -c /gale/netapp/seq2/illumina_runs/.config/180709_K00161_0224_AHVMNJBBXX"
echo "-c	path to config directory."
echo "-h	this help message"
}

while getopts ":f:c:h" opt; do
  case $opt in
    c)config_path=$OPTARG
      ;;
    h)
      usage
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      usage
      exit 1
      ;;
  esac
done

source "$config_path"

#if no argument (empty string) is given for the run directory, assume the run 
#directory has the same name as the unaligned directory without the timestamp
#if [ -z "$name" ] ; then
#  bcl_path="$(echo $bcl_path | awk '{print substr($0, 1, length($0)-13)}')"
#fi



stats="$bcl_path/Stats/Stats.json"

#cat Stats.json | jq '.ReadInfosForLanes[0].ReadInfos[0].NumCycles'

[ -f $runparameters ] || runparameters="$bcl_path/RunParameters.xml"

projects="$(lanebarcode-projects -l $lanebarcode)"

samples="$(lanebarcode-samples -l $lanebarcode)"

qsub_command="$(cat $fastq_path/$QSUB_FILE)"

node="$(cat $fastq_path/$QSTAT_FILE)"

jobid="$(awk '{print $1}' $fastq_path/$QSTAT_FILE)"

#jobmetrics="$bcl_path/job_metrics.txt"
jobmetrics="$qsub_path/job_metrics.txt"

qacct -d 2 -o seq -j | grep -A 34 $jobid | grep -E "jobnumber|_time|slots|^mem|maxvmem" > $jobmetrics

jobnumber=$(grep "jobnumber" $jobmetrics)
start_time=$(grep "start_time" $jobmetrics)
end_time=$(grep "end_time" $jobmetrics)
slots=$(grep "slots" $jobmetrics)
mem=$(grep "^mem" $jobmetrics)
maxvmem=$(grep "maxvmem" $jobmetrics)

echo $bcl2fastq_commandline

{
  echo -e "Demux complete.\n" ; \
  echo -e " Path to fastq:" ; \
  echo -e "$fastq_path\n" ; \
  echo -e "Samples:" ; \
  echo -e "$samples\n" ; \
  echo -e "Projects:" ; \
  echo -e "$projects\n" ; \
  echo -e "Path to bcl:" ; \
  echo -e "$bcl_path\n" ;\
  echo -e "Command-line invocation:" ; \
  echo -e "$bcl2fastq_commandline\n" ; \
  echo -e "SGE invocation:" ; \
  echo -e "$qsub_command\n" ; \
#  echo -e "Node:" ; \
#  echo -e "$node\n" ;\
  echo -e "$jobnumber" ;\
  echo -e "$start_time" ;\
  echo -e "$end_time" ;\
  echo -e "$slots" ;\
  echo -e "$mem" ;\
  echo -e "$maxvmem" ;\
  echo -e
} | mailx -s "$bcl_dir" -a "$lanebarcode" -a "$samplesheet_path" -a "$runinfo" -a "$runparameters" -c "$cc" "$RECIPIENT"
