#!/bin/bash
#input: bcl2fastq_command line string
#output: bcl2fastq-config file containing variables for the run


var2file () {
#input: variable name and path to config file
#output: file 
varname=$1 
config=$2
echo "$varname=\"${!varname}\"" >> $config
#https://stackoverflow.com/questions/10990436/bash-concatenating-2-strings-to-reference-a-3rd-variable
}

