#!/bin/bash
#
#usage:
#
#submit2q commandline2submit qsubpath qsubdir dir2chk
#
#input: path to bcl2fastq-config file
#

source "/gale/netapp/home/seq/bin/demux/demux-constants"
source "/gale/netapp/home/seq/bin/demux/date-time"
status_parent="/gale/netapp/seq2/illumina_runs/.status/"

submit2q () {

  #arguments passed to function
  commandline2submit="$1"
  qsubpath="$2"
  qsubdir="$3"
  dir2chk="$4"

  if echo $commandline2submit | grep -q rsync ; then
    sge_threads=1
    sge_vmem=2G
    status_file="rsynced"

  elif echo $commandline2submit | grep -q upload ; then
    sge_threads=15
    sge_vmem=1G
    status_file="uploaded"

  fi
 
  ERROR_MESSAGE="$(date_time) ERROR: A previous attempt to submit this job has been detected. Check this directory:"

  #check if the job was previously submitted to the que  
  if [ -d $qsubpath ] ; then
    echo "$ERROR_MESSAGE"
    echo "$qsubpath"
    echo

  #check if the directory exists
  elif [[ ! -z $dir2chk &&  -d "$dir2chk" ]] ; then
    echo "Directory exists."
    echo "$ERROR_MESSAGE"
    echo "$dir2chk"
    echo 
 
  else
    echo "$(date_time) INFO: $dir2chk does not exist"
    echo
    echo "$(date_time) INFO: $qsubpath does not exist"
    echo
    echo "$(date_time) INFO: Submitting job."
    
    #prepare submission dir
    echo "$(date_time) INFO: Making qsub directory: $qsubpath"
    mkdir $qsubpath
    cd $qsubpath
    
    #write commandline2submit to commands script file
    echo "$commandline2submit" >> $qsubpath/$QSUB_COMMANDS_SCRIPT
    
    echo "$(date_time) INFO: Submitting to the queue."
    
    echo "$(date_time) INFO: $(echo $commandline2submit)"
    
    ls -l "$QUEUECONFIG"
    
    2q -c $QUEUECONFIG -t $sge_threads -v $sge_vmem
    
    jobid="$(qstatx | grep "$qsubdir" | awk '{print $1}')"
    
    echo $node
    
    q_submission_file="$qsubpath/$COMMANDS2SUBMIT"
    
    qsub_command_string=$(cat $q_submission_file)
    
    echo "$(date_time) INFO: Job submittted. Sending notification email."
    
    {
    echo -e "Command-line invocation:" ; \
    echo -e "$commandline2submit\n" ; \
    echo -e "SGE invocation:" ; \
    echo -e "$qsub_command_string\n" ; \
    echo -e "jobnumber:" ; \
    echo -e "$jobid\n" ; \
    echo -e "SGE logs:" ; \
    echo -e "$qsubpath"
    } | mailx -s "$bcl_path" -c $CC "$RECIPIENT"
  
  fi
  
}
